add public address handling to PNP
ow2-proactive/programming pull request #1334
Opened 2017-04-28 15:03 UTC by fviale

- Added proactive.net.public_address setting. It allows to specify a hostname or ip address which can be used to contact the Remote Objects.
 - This configuration is implemented in the PNP protocol only. In case this setting is configured, the PNP protocol creates urls like pnp://public_address@private_address:port
 - To contact a Remote Object which contains a public address, the pnp protocol tries first to open a socket to the private address, and if the connection fails, it will create a socket to the public address.
 - URIBuilder methods now have userInfo and query parameters
 - Better escaping of urls in jmx FactoryName
 - added a functional test TestPNPPublicAddress

2017-04-28 16:19 UTC, vinseon requested changes
Nice improvements overall

2017-04-28 16:19 UTC, vinseon commented on programming-extensions/programming-extension-pnp/src/main/java/org/objectweb/proactive/extensions/pnp/PNPRemoteObjectFactoryBackend.java
> +                              ProActiveInet.getPublicAddress(),
I think we should explicitly indicate here that the public IP address is intentionally given through the "UserInfo" field and explain why (namespace issue using the 'query' field ?).

2017-05-02 08:02 UTC, fviale commented
Retest this please

2017-05-02 13:55 UTC, paraita approved these changes
Works but I had to run the spotlessApply task on my machine for the tests to pass

2017-05-03 15:22 UTC, vinseon approved these changes

2017-05-06 03:51 UTC, merged