Add stderr in logs in case of failure destroying forked process
ow2-proactive/programming pull request #1346
Opened 2017-10-04 12:48 UTC by marcocast

2017-10-04 13:57 UTC, fviale commented on programming-extensions/programming-extension-processbuilder/src/main/java/org/objectweb/proactive/extensions/processbuilder/LinuxProcessBuilder.java
> +                logger.warn("Failed to destroy OS process with token: " + this.token, e);
I would rather do 
logger.warn("Failed to destroy OS process with token: " + this.token, e);
printStdout(p, Level.WARN);
printStderr(p, Level.WARN);

2017-10-04 14:01 UTC, fviale commented on programming-extensions/programming-extension-processbuilder/src/main/java/org/objectweb/proactive/extensions/processbuilder/LinuxProcessBuilder.java
> +                    if (Level.DEBUG == logLevel) {
better to do this in a single line
logger.log(logLevel, "token: " + this.token + " " + messageType + ":" + line)

2017-10-04 14:01 UTC, fviale requested changes
two small comments, see inline messages

2017-10-04 14:10 UTC, fviale approved these changes

2017-10-05 06:10 UTC, paraita approved these changes

2017-10-05 07:08 UTC, merged